### ISSUE TITLE
Add a namespace for 3rd party modules

### ISSUE THREAD

**Issue by oalders** [hayajo/Mojolicious-Plugin-Web-Auth#17]
This is related to #15.  What do you think about supporting another namespace for 3rd party modules?  That way I could upload modules for Spotify, Fitbit etc without adding to your support burden.  The way things are currently set up, I'd need to step on your namespace to release my own modules for other OAuth services.

The problem is, I can't actually think of a good namespace for this. :frowning: 

Or, I could upload some new modules in the current namespace and give you co-maint so that you could easily include them with your distribution at some point in the future, should you want to.

What do you think?

**Comment by oalders** [comment]
I had a closer look and realized it made sense to use something like Mojolicious::Plugin::Web::Auth::Site::Contrib::Foo

**Comment by hayajo** [comment]
I am sorry for taking rather a while to reply to it. 

Please use "Mojolicious::Plugin::Web::Auth::Site" Namespace (e.g. Mojolicious::Plugin::Web::Auth::Site::Box).

**Comment by oalders** [comment]
@hayajo OK, thanks.  I'll re-release it under that namespace. :)
