### ISSUE TITLE
::Twitter adds crufy keys to the session 

### ISSUE THREAD

**Issue by guest20** [hayajo/Mojolicious-Plugin-Web-Auth#29]
After testing the login-with-twitter workflow a bundle of times (nearly 20), I discovered that I have a 1859 byte cookie and a session full of random token pairs.

It would be nice if either
 - the tokens were in a different namespace
 - there was some cleanup
 - or I could control their storage manually.

I believe this could be avoided by giving more control over the `session` argument to `Net::OAuth::Client->new`.

I'm not sure if these things should be secret or not (cookies aren't secret), but I'm sure that tricking someone into requesting `/auth/twitter/authenticate` a bundle of times would bloat out their cookie to 4k and cause mojo to stop updating it.

**Comment by hayajo** [comment]
Thank you!
I will investigate.

**Comment by hayajo** [comment]
ver 0.14 shipped.

https://metacpan.org/release/HAYAJO/Mojolicious-Plugin-Web-Auth-0.14

Please try this version.
